package com.example.apiden.shared.api;

import io.micronaut.serde.annotation.Serdeable;
import io.micronaut.sourcegen.annotations.Builder;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;

/**
 * The top-level root object for the API communication envelope.
 * It contains metadata about the client context and the server processing context.
 *
 * @param client Information about the client context.
 * @param server Information about the server context.
 */
@Serdeable
@Builder
final record ApiObject(Client client, Server server) {
}

/**
 * Information about the client that initiated the request.
 *
 * @param http HTTP-specific client info.
 * @param request Request-specific client info.
 * @param response Response-specific client info.
 * @param info Any additional client-side info.
 */
@Serdeable
@Builder
final record Client(ClientHttp http, ClientRequest request, ClientResponse response, Map<String, Object> info) {
}

/**
 * HTTP-specific metadata from the client side, such as headers.
 *
 * @param headers The HTTP headers.
 */
@Serdeable
@Builder
final record ClientHttp(Map<String, List<String>> headers) {
}

/**
 * Transactional request information provided by the client.
 *
 * @param traceid The client-provided trace identifier.
 * @param timestamp The request timestamp.
 * @param body The request body payload.
 */
@Serdeable
@Builder
final record ClientRequest(String traceid, OffsetDateTime timestamp, String language, Object body) {
}

/**
 * Transactional response information as seen/expected by the client.
 *
 * @param timestamp The response timestamp.
 * @param duration The execution duration as string.
 */
@Serdeable
@Builder
final record ClientResponse(OffsetDateTime timestamp, String duration) {
}

/**
 * Information about the server's processing of the request.
 *
 * @param http HTTP-specific server info.
 * @param request Request-specific server info.
 * @param response Response-specific server info.
 * @param info Any additional server-side info.
 */
@Serdeable
@Builder
final record Server(ServerHttp http, ServerRequest request, ServerResponse response, Map<String, Object> info) {
}

/**
 * HTTP-specific metadata from the server side.
 *
 * @param status The HTTP status code.
 * @param headers The HTTP headers.
 */
@Serdeable
@Builder
final record ServerHttp(Integer status, Map<String, List<String>> headers) {
}

/**
 * Transactional request information captured by the server.
 *
 * @param timestamp The request timestamp.
 * @param traceid The server-resolved trace identifier.
 */
@Serdeable
@Builder
final record ServerRequest(OffsetDateTime timestamp, String traceid) {
}

/**
 * Transactional response information generated by the server.
 *
 * @param timestamp The response timestamp.
 * @param duration The execution duration.
 * @param status High-level status.
 * @param code Response code.
 * @param message Response message.
 * @param body Response body payload.
 */
@Serdeable
@Builder
final record ServerResponse(OffsetDateTime timestamp, String duration, String language, String status, String code,
        String message, Object body) {
}
