# app name
micronaut.application.name=apiden

# i18n configuration
micronaut.i18n.resource-bundle.base-names=messages
micronaut.server.locale-resolution.default-locale=en
micronaut.server.locale-resolution.cookie.enabled=true
micronaut.server.locale-resolution.cookie.cookie-name=LOCALE

# app instance name
application.instance.name=apiden-instance-1

# api envelope includes
application.api.envelope.include-client-headers=true
application.api.envelope.include-server-headers=true
application.api.envelope.include-stacktrace=true
application.api.envelope.include-client-info=true
application.api.envelope.include-server-info=true

# log level
application.log.level.root=INFO
application.log.level.com.example.apiden=INFO

# live update config
application.configuration.live-update.enabled=true
application.configuration.live-update.list=application.api.envelope.include-client-headers,application.api.envelope.include-server-headers,application.api.envelope.include-stacktrace,application.api.envelope.include-client-info,application.api.envelope.include-server-info,application.log.level.root,application.log.level.com.example.apiden