# app name
micronaut.application.name=apiden
micronaut.server.context-path=/api

# i18n configuration
micronaut.i18n.resource-bundle.base-names=messages
micronaut.server.locale-resolution.default-locale=en
micronaut.server.locale-resolution.cookie.enabled=true
micronaut.server.locale-resolution.cookie.cookie-name=LOCALE

# log level
logger.levels.root=INFO
logger.levels.com.example.apiden=INFO

# app instance name
application.instance.name=apiden-instance-1

# api response includes
application.api.response.include-metadata=true
application.api.response.include-stacktrace=true
application.api.response.include-environment-info=true

# live update config
application.configuration.live-update.enabled=true
application.configuration.live-update.list=\
  application.api.response.include-metadata,\
  application.api.response.include-stacktrace,\
  application.api.response.include-environment-info

# Management Endpoints
endpoints.all.enabled=true
endpoints.all.sensitive=false
endpoints.loggers.write-sensitive=false

# Metrics & Prometheus
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.export.prometheus.descriptions=true
micronaut.metrics.export.prometheus.step=PT1M

# OpenAPI / Swagger UI
micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**
micronaut.router.static-resources.swagger-ui.paths=classpath:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**
